# Generated by Django 5.1.4 on 2025-01-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0002_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translationrequest",
            name="translation_type",
            field=models.CharField(
                choices=[
                    ("DOCUMENT", "Document"),
                    ("LIVE_ON_SITE", "Live On Site"),
                    ("REMOTE_PHONE", "Remote Phone"),
                    ("REMOTE_MEETING", "Remote Meeting"),
                ],
                max_length=20,
            ),
        ),
    ]
