# Generated by Django 5.1.4 on 2025-01-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0003_alter_translationrequest_translation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordreset",
            name="token",
            field=models.CharField(max_length=6),
        ),
    ]
