# Generated by Django 5.1.4 on 2025-01-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0004_alter_passwordreset_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="token",
            field=models.CharField(max_length=6),
        ),
    ]
